### ISSUE TITLE
Hyperion for Windows

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion.ng#737]
## Feature request

This is a step tracking issue for full Windows support. Everyone can grab a task, the order is free (as possible). \
**Windows support is still experimental**

- [x] Compilation (Hyperion can be compiled) #738 
- [x] Documentation (To recreate a basic compilation system) #738 
- [ ] Running (Hyperion runs without critical issues)
- [x] CI - Azure (Compile Hyperion on Azure)
- [x] CI - GH Actions (Compile Hyperion on Github Actions)
- [x] Packaging (.zip) (All in one .zip to provide artifacts)
- [x] Packaging NSIS (.exe). Installer for Hyperion
- [ ] Testing - Test everything
- [x] Release

### Related PRs
[738](https://github.com/hyperion-project/hyperion.ng/pull/738)

### Known issues
As of 2.0.0-alpha.7
- ~Logger won't print all to terminal~
- ~`hyperiond -d` crashes~
- ~`qt.network.ssl QSslSocket: Can't resolve function d2i_x509`. Requires bundled openssl lib(s)~
- ~You need to install latest vcredist x64; Should be executed with the setup install.~
- No fast DirectX capture, just slow QtGrabber for screen capturing (but works basically)
- Crash after OS standby (in this case Windows 7 "energy saving")

### Tests
- [x] SSDP Server works
- [x] Serialport fixed with #837 
- [x] SSL Server works #864

**Comment by Paulchen-Panther** [comment]
How may I understand that? Under WSL (Windows Subsystem for Linux) or complete Windows binary

**Comment by Paulchen-Panther** [comment]
Should the end result be a windows executable?

**Comment by brindosch** [comment]
Yes

**Comment by Paulchen-Panther** [comment]
Should this represent a new project or should it be integrated into the current one?

**Comment by brindosch** [comment]
I assume we compile the current code on Windows.

**Comment by Paulchen-Panther** [comment]
> I assume we compile the current code on Windows.
But that would inflate the base a lot?
To get started:
What speaks against CMake?

**Comment by brindosch** [comment]
I already explored the topic.

![windows](https://user-images.githubusercontent.com/15967679/77461261-9494ef80-6e02-11ea-8a11-300ecad3ec6d.PNG)

**Comment by Paulchen-Panther** [comment]
Which build system do you use?

**Comment by brindosch** [comment]
cmake with msvc 2017

**Comment by Paulchen-Panther** [comment]
Are you going to publish the whole thing?

**Comment by VyacheslavTeplyakov** [comment]
Hi!
I tested the Windows version. Unable to start, initialize my usb grabber. The device is detected in the system as a webcam.
In Linux it is detected as follows. And it works fine.
/dev/snd/controlC2 - MACROSILICON_USB_Video
/dev/video1 - MACROSILICON_USB_Video
/dev/video0 - MACROSILICON_USB_Video
